// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {bot} from '../models';
import {config} from '../models';
import {main} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<updater.Status>;

export function ClearSkippedVersion():Promise<void>;

export function DownloadUpdate():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetAttackHistory():Promise<Array<bot.AttackReport>>;

export function GetConfig():Promise<config.BotConfig>;

export function GetLogs():Promise<Array<string>>;

export function GetStats():Promise<bot.BotStats>;

export function GetStrategies():Promise<Array<string>>;

export function GetUpdateStatus():Promise<updater.Status>;

export function InstallAndRestart():Promise<void>;

export function IsRunning():Promise<boolean>;

export function ResetStats():Promise<void>;

export function SaveConfig(arg1:number,arg2:number,arg3:number,arg4:boolean,arg5:string,arg6:boolean,arg7:number):Promise<void>;

export function SetStrategyArmySlot(arg1:string,arg2:number):Promise<void>;

export function SetStrategyAutoEnd(arg1:string,arg2:boolean):Promise<void>;

export function SkipCurrentVersion():Promise<void>;

export function StartBot(arg1:number,arg2:number,arg3:number,arg4:boolean,arg5:boolean):Promise<main.BotStatus>;

export function StopBot():Promise<main.BotStatus>;
