// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearSkippedVersion() {
  return window['go']['main']['App']['ClearSkippedVersion']();
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAttackHistory() {
  return window['go']['main']['App']['GetAttackHistory']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStrategies() {
  return window['go']['main']['App']['GetStrategies']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function InstallAndRestart() {
  return window['go']['main']['App']['InstallAndRestart']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function ResetStats() {
  return window['go']['main']['App']['ResetStats']();
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SkipCurrentVersion() {
  return window['go']['main']['App']['SkipCurrentVersion']();
}

export function StartBot(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartBot'](arg1, arg2, arg3, arg4, arg5);
}

export function StopBot() {
  return window['go']['main']['App']['StopBot']();
}
